name: stories_editor
description: This is a package created in the style of the instagram story creator, with which you can create images with images, texts, stickers (Gifs), finger drawing.
version: 0.2.2
homepage: https://github.com/camilo1498/stories_editor

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.0.4
  # image
  image: ^3.2.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  # with this ref fix `Looking up a deactivated widget's ancestor is unsafe`.
  #photo_view:
  #  git:
  #    url: https://github.com/bluefireteam/photo_view
  #    ref: 8156907eecfa812b181a5a729d790f6d399f311b
  image_gallery_saver: ^1.7.1
  #own packages
  gallery_media_picker: ^0.0.82


  modal_gif_picker: ^0.0.2
  # painting
  perfect_freehand: ^1.0.4
  # positioning
  align_positioned: ^3.0.0
  #message
  fluttertoast: ^8.1.1

  animated_text_kit: ^4.2.2

  flutter_screenutil: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  assets:
    - packages/stories_editor/assets/icons/align_center.png
    - packages/stories_editor/assets/icons/align_left.png
    - packages/stories_editor/assets/icons/align_rigth.png
    - packages/stories_editor/assets/icons/arrow.png
    - packages/stories_editor/assets/icons/brush.png
    - packages/stories_editor/assets/icons/check.png
    - packages/stories_editor/assets/icons/circular_gradient.png
    - packages/stories_editor/assets/icons/colorpalette.png
    - packages/stories_editor/assets/icons/download.png
    - packages/stories_editor/assets/icons/draft.png
    - packages/stories_editor/assets/icons/draw.png
    - packages/stories_editor/assets/icons/font_backGround.png
    - packages/stories_editor/assets/icons/marker.png
    - packages/stories_editor/assets/icons/neon.png
    - packages/stories_editor/assets/icons/pen.png
    - packages/stories_editor/assets/icons/pickColor.png
    - packages/stories_editor/assets/icons/return.png
    - packages/stories_editor/assets/icons/stickers.png
    - packages/stories_editor/assets/icons/text.png
    - packages/stories_editor/assets/icons/trash.png
    - packages/stories_editor/assets/icons/photo_filter.png
    - packages/stories_editor/assets/icons/video_trim.png
    - packages/stories_editor/assets/images/instagram_logo.png

  fonts:

    - family: Alegreya
      fonts:
        - asset: packages/stories_editor/assets/fonts/Alegreya-VariableFont_wght.ttf

    - family: B612
      fonts:
        - asset: packages/stories_editor/assets/fonts/B612-Regular.ttf

    - family: TitilliumWeb
      fonts:
        - asset: packages/stories_editor/assets/fonts/TitilliumWeb-Regular.ttf

    - family: Varela
      fonts:
        - asset: packages/stories_editor/assets/fonts/Varela-Regular.ttf

    - family: Vollkorn
      fonts:
        - asset: packages/stories_editor/assets/fonts/Vollkorn-Regular.ttf

    - family: Rakkas
      fonts:
        - asset: packages/stories_editor/assets/fonts/Rakkas-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: packages/stories_editor/assets/fonts/ConcertOne-Regular.ttf

    - family: YatraOne
      fonts:
        - asset: packages/stories_editor/assets/fonts/YatraOne-Regular.ttf

    - family: OldStandardTT
      fonts:
        - asset: packages/stories_editor/assets/fonts/OldStandardTT-Italic.ttf

    - family: Neonderthaw
      fonts:
        - asset: packages/stories_editor/assets/fonts/Neonderthaw-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: packages/stories_editor/assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: SedgwickAve
      fonts:
        - asset: packages/stories_editor/assets/fonts/SedgwickAve-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: packages/stories_editor/assets/fonts/IndieFlower-Regular.ttf

    - family: Sacramento
      fonts:
        - asset: packages/stories_editor/assets/fonts/Sacramento-Regular.ttf

    - family: PressStart2P
      fonts:
        - asset: packages/stories_editor/assets/fonts/PressStart2P-Regular.ttf

    - family: FrederickatheGreat
      fonts:
        - asset: packages/stories_editor/assets/fonts/FrederickatheGreat-Regular.ttf

    - family: ReenieBeanie
      fonts:
        - asset: packages/stories_editor/assets/fonts/ReenieBeanie-Regular.ttf

    - family: BungeeShade
      fonts:
        - asset: packages/stories_editor/assets/fonts/BungeeShade-Regular.ttf

    - family: UnifrakturMaguntia
      fonts:
        - asset: packages/stories_editor/assets/fonts/UnifrakturMaguntia-Regular.ttf